spring:
  application:
    name: task-manager-api
  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:43138/beehome
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: QIuYGwjjCGWxhxbmXHVKEwciwWaYsegy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
  error:
    include-message: always
spring-doc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
jwt:
  secret: "k+lD7Op9TcFVxQX7+WT+g3OzP1V3OdR9eFtDT7u7Qc4="
  expiration: 3600000 # 1 hora